// <auto-generated />
using InfraEstrutura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfraEstrutura.Migrations
{
    [DbContext(typeof(SistemaDbContext))]
    partial class SistemaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Entity.Tecnologia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescricaoTecnologia")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("TipoTecnologiaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoTecnologiaId");

                    b.ToTable("Tecnologia");
                });

            modelBuilder.Entity("Dominio.Entity.TipoTecnologia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("TipoTecnologia");
                });

            modelBuilder.Entity("Dominio.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Empresa")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("TipoTecnologiaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoTecnologiaId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Dominio.Entity.Tecnologia", b =>
                {
                    b.HasOne("Dominio.Entity.TipoTecnologia", "TipoTecnologia")
                        .WithMany("Tecnologias")
                        .HasForeignKey("TipoTecnologiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoTecnologia");
                });

            modelBuilder.Entity("Dominio.Entity.User", b =>
                {
                    b.HasOne("Dominio.Entity.TipoTecnologia", "TipoTecnologia")
                        .WithMany("Users")
                        .HasForeignKey("TipoTecnologiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoTecnologia");
                });

            modelBuilder.Entity("Dominio.Entity.TipoTecnologia", b =>
                {
                    b.Navigation("Tecnologias");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
